experiment:
  lighting_height_mm: 90.0
  led_brightness: 1.0
  camera_height_mm: 420.0
  camera_aperture_f_number: 5.5
  camera_focus_distance_m: 0.37

camera:
  AcquisitionMode: "Continuous"
  TriggerMode: "Off"
  PixelFormat: "BayerRG8"

  ExposureAuto: "Off"
  ExposureTime: 30000.0

  GainAuto: "Off"
  Gain: 0.0

  BalanceWhiteAuto: "Off"